### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference       

### ISSUE THREAD

**Issue by shawndube** [opentok/accelerator-textchat-android#45]
## New issue checklist

- [x ] I have read all of the [`README`](../README.md) 
- [x ] I have searched [existing issues](https://github.com/opentok/accelerator-textchat-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
    implementation 'com.opentok.android:opentok-accelerator-core:1.0.21'
    implementation 'com.opentok.android:opentok-accelerator-textchat:1.0.4'
- iOS/Android/Browser version(s): Android 7, probably others
- Devices/Simulators/Machine affected: Galaxy S7
- Reproducible in the demo project? (Yes/No): (not tried)
- Related issues:

## Bug report
Getting a crash report from Crashlytics
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

#### Expected behavior

> Open text chat and use normally

#### Actual behavior

> Crash

#### Steps to reproduce

> unk. but code does not null-check the getContext() call which can return null in certain situations.

#### Crash log? Screenshots? Videos? Sample project?

>Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at com.tokbox.android.accpack.textchat.TextChatFragment.init(TextChatFragment.java:345)
       at net.theretrocompany.android.retrobeauty.ConsultationSession$3.onConnected(ConsultationSession.java:516)
       at net.theretrocompany.android.retrobeauty.ConsultationSession$3.onConnected(ConsultationSession.java:502)
       at com.tokbox.android.otsdkwrapper.listeners.PausableBasicListener$2.run(PausableBasicListener.java:62)
       at com.tokbox.android.otsdkwrapper.listeners.PausableBasicListener$1.run(PausableBasicListener.java:48)
       at com.tokbox.android.otsdkwrapper.listeners.PausableBasicListener.runUIListenerTask(PausableBasicListener.java:53)
       at com.tokbox.android.otsdkwrapper.listeners.PausableBasicListener.onConnected(PausableBasicListener.java:59)
       at com.tokbox.android.otsdkwrapper.wrapper.OTWrapper$1.onConnected(OTWrapper.java:1074)
       at com.tokbox.android.otsdkwrapper.wrapper.OTAcceleratorSession.onConnected(OTAcceleratorSession.java:312)
       at com.opentok.android.Session$3.run(Session.java:1461)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

## Question or Feature Request

> ...

**Comment by marinaserranomontes** [comment]
Hi @shawndube ,

Sorry for the delayed response.

I think the problem could be related to the moment where you are initialising the TextChatFragment.
It should be happening if the "savedInstanceState" is not null.

You can find a sample about how to integrate the text-chat fragment here:
https://github.com/opentok/accelerator-sample-apps-android/blob/master/AcceleratorSampleApp/app/src/main/java/com/tokbox/android/accelerator/sample/MainActivity.java

Regards,
Marina

**Comment by igorwojda** [comment]
We are currently cleaning and bringing accelerators up to date. This is quite old issue, and it looks like `TextChatFragment` was incorrectly initialised on client side. I will close this issue for now. If the problem still exists please let us know.
